spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ahmedhachemi
    username: ahmedhachemi
    password: ahmedhachemi
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
