CREATE TABLE bien_immobilier (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    reference VARCHAR(255) NOT NULL,
    cour VARCHAR(255) NOT NULL,
    sale_date_unix TIMESTAMP NOT NULL,
    sale_date TIMESTAMP NOT NULL,
    type VARCHAR(255) NOT NULL,
    description TEXT,
    status VARCHAR(50) NOT NULL,
    surface DOUBLE PRECISION,
    starting_price DOUBLE PRECISION NOT NULL,
    ending_price DOUBLE PRECISION,
    commune VARCHAR(255) NOT NULL,
    code_postal VARCHAR(20),
    numero_voie VARCHAR(20),
    nom_voie VARCHAR(255),
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    visits INT,
    url VARCHAR(1024),
    avocat_nom VARCHAR(255),
    avocat_numero_voie VARCHAR(20),
    avocat_nom_voie VARCHAR(255),
    avocat_code_postal VARCHAR(20),
    avocat_commune VARCHAR(255),
    avocat_phone_number VARCHAR(50),
    avocat_email VARCHAR(255),
    annexes TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    code_commune_insee VARCHAR(20),
    nombre_chambre INT,
    avocat_nickname VARCHAR(255),
    dpe VARCHAR(50),
    estimation DOUBLE PRECISION,
    google_street_view VARCHAR(1024)
);
