name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test_user"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Définir les variables d'environnement
        run: |
          echo "DB_HOST=localhost" >> $GITHUB_ENV
          echo "DB_PORT=5432" >> $GITHUB_ENV
          echo "DB_NAME=test_db" >> $GITHUB_ENV
          echo "DB_USER=test_user" >> $GITHUB_ENV
          echo "DB_PASS=test_password" >> $GITHUB_ENV
          echo "SPRING_MAIN_LOG-LEVEL=DEBUG" >> $GITHUB_ENV

      - name: Attendre que PostgreSQL soit prêt
        run: |
          for i in {1..30}; do
            nc -z localhost 5432 && echo "PostgreSQL est prêt" && exit 0
            echo "En attente de PostgreSQL..."
            sleep 2
          done
          echo "Échec : PostgreSQL n'est pas accessible" && exit 1

      - name: Vérifier la connexion PostgreSQL
        run: |
          PGPASSWORD=$DB_PASS psql -h localhost -U $DB_USER -d $DB_NAME -c "SELECT 'PostgreSQL connecté!'"

      - name: Afficher `application-test.yml`
        run: cat src/test/resources/application-test.yml

      - name: Activer les logs détaillés
        run: echo "SPRING_MAIN_LOG-LEVEL=DEBUG" >> $GITHUB_ENV
    
      - name: Build et tests
        run: mvn clean verify -X