name: CI/CD Spring Boot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compilation et tests
        run: mvn clean package

      - name: Upload du JAR
        uses: actions/upload-artifact@v3
        with:
          name: spring-boot-app
          path: target/*.jar
